version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Agrega este comando para iniciar en modo desarrollo
    command: npm run start:dev
    ports:
      - '3000:3000'   # El puerto por defecto de NestJS es 3000
      - '9229:9229'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - rayuela_net
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME={MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD={MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rayuela_net
volumes:
  mongodb_data:

networks:
  rayuela_net:
    external: true
